wip

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -70,6 +70,7 @@ jobs:
         fetch-depth: 2
     - name: Build or fetch XLA CPU PJRT plugin
       run: |
+        exit 1;
         if [ ! "$(git diff --exit-code HEAD^ XLA_VERSION)" ]; then
           . ./dev.sh
           rev=$(cat XLA_VERSION)
@@ -120,6 +121,7 @@ jobs:
           fetch-depth: 2
       - name: Build or fetch XLA CUDA PJRT plugin
         run: |
+          exit 1;
           if [ ! "$(git diff --exit-code HEAD^ XLA_VERSION)" ]; then
             . ./dev.sh
             rev=$(cat XLA_VERSION)
@@ -166,16 +168,14 @@ jobs:
       - uses: actions/checkout@v4
       - name: Install build dependencies
         run: |
-          brew install chezscheme gmp  # coreutils is broken on arm64, and it's only a nice-to-have
+          brew install chezscheme
           git clone https://github.com/stefan-hoeck/idris2-pack.git
           (cd idris2-pack && make micropack SCHEME=chez)
-          export PATH="$HOME/.pack/bin:$HOME/.idris2/bin:$PATH"
-          pack switch HEAD
+          ~/.pack/bin/pack switch HEAD
       - name: Build tests
         working-directory: test/xla-cpu
         run: |
-          export PATH="$HOME/.pack/bin:$HOME/.idris2/bin:$PATH"
-          SPIDR_INSTALL_SUPPORT_LIBS=false pack --no-prompt build xla-cpu.ipkg
+          SPIDR_INSTALL_SUPPORT_LIBS=false ~/.pack/bin/pack --no-prompt build xla-cpu.ipkg
           tar cfz tests-xla-cpu.tar.gz -C build/exec .
       - name: Upload tests
         uses: actions/upload-artifact@v4
@@ -232,11 +232,9 @@ jobs:
       uses: actions/download-artifact@v4
       with:
         merge-multiple: true
-    - name: Install runtime dependencies
-      run: |
-        brew install chezscheme
     - name: Run tests
       run: |
+        brew install chezscheme  # moving this here because GH actions is repeatedly failing 
         tar xfz tests-xla-cpu.tar.gz && rm tests-xla-cpu.tar.gz
         ./test
   test-xla-cuda-linux:
